### ISSUE TITLE
BDSKY 1.3.3 release breaks backward compatibility of XML files built with previous BDSKY module versions

### ISSUE THREAD

**Issue by gattil** [BEAST2-Dev/bdsky#17]
XML files built with BDSKY version prior 1.3.3 generate the following error during execution.

```
Error 130 parsing the xml input file

nullThis BEASTInterface (BirthDeathSkySerial.t:clean_H1N1_NA) has no input with name R0. Choose one of these inputs: birthRateChangeTimes,deathRateChangeTimes,samplingRateChangeTimes,removalProbabilityChangeTimes,intervalTimes,birthRateTimesRelative,deathRateTimesRelative,samplingRateTimesRelative,reverseTimeArrays,rhoSamplingTimes,origin,originIsRootEdge,conditionOnRoot,birthRate,deathRate,samplingRate,removalProbability,rho,contemp,reproductiveNumber,becomeUninfectiousRate,samplingProportion,netDiversification,turnOver,forceRateChange,conditionOnSurvival,conditionOnRhoSampling,tree,treeIntervals
```

Temporary fix: manually search and replace `R0` with `reproductiveNumber` in the XML file

**Comment by tgvaughan** [comment]
Wow, sorry that nobody got back to you for such a long time, Lorenzo.  I don't think we should worry too much about this any more though.  Backwards compatibility is important, but I think the current naming is well enough established for us not to start adding compatibility with the older naming now.
