### ISSUE TITLE
BDSKY for HIV

### ISSUE THREAD

**Issue by antoine4ucsd** [BEAST2-Dev/bdsky#22]
Hello
I am setting up a new analysis for a large set of HIV data and I was wondering which clock rates params you would suggest for serially sampled data
UCLN or strick?
and for the clock.rate and ucldMmean priors, which distribution? LogNormal? gamma? others? 

thanks for the advices
a

**Comment by tgvaughan** [comment]
Hi @antoine4ucsd, sorry that nobody got back to you, but it's likely that nobody saw your as BDSKY is essentially "finished".  These kinds of questions are best directed to the beast-users email list.
