### ISSUE TITLE
BDSKY_contemptreeScaler.t:$(n) in BDSKY_contemp.xml and BDSKY_multiRho.xml

### ISSUE THREAD

**Issue by rbouckaert** [BEAST2-Dev/bdsky#25]
Greetings from Taming the BEAST down under. This duplication in names causes the scale operator to be incorporated or not at random when the BDSKY_contemp prior is chosen, thus causing problems with the skyline tutorial (https://taming-the-beast.org/tutorials/Skyline-plots/). There are probably other operators that cause problems, so better check the uniqueness of operator names in these templates.

**Comment by denisekuehnert** [comment]
Thanks, fixed in new release v1.4.4.

**Comment by tgvaughan** [comment]
For some reason that I can't understand, this realease breaks the [Setting Priors](https://taming-the-beast.org/tutorials/Prior-selection/) TTB tutorial.  It is no longer possible to load in the existing Homochronous.xml, add a tMRCA prior on the root, and export it successfully, as doing this results in a number of parameters being removed from the `<state>` block.

I've tried redoing the tutorial from scratch with the new BDSKY release to generate new XMLs, and the same problem occurs.  The problem does not occur with v1.4.3.

Here is the exported from BEAUti before the modification: [Homochronous.xml.txt](https://github.com/BEAST2-Dev/bdsky/files/2945415/Homochronous.xml.txt).

Here is the file exported from BEAUti after the addition of the tMRCA prior: [Homochronous_tMRCA.xml.txt](https://github.com/BEAST2-Dev/bdsky/files/2945427/Homochronous_tMRCA.xml.txt).

Here is the file generated by loading in Homochronous.xml, adding the tMRCA, then exporting [Homochronous_tMRCA_broken.xml.txt](https://github.com/BEAST2-Dev/bdsky/files/2945428/Homochronous_tMRCA_broken.xml.txt).

Any help would be hugely appreciated!

**Comment by denisekuehnert** [comment]
Looks like i missed some IDs that were still duplicates. Should be fixed now with the new TreePriorsBDSKY template.

**Comment by tgvaughan** [comment]
Thanks Denise!
