### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by StephanieRodrigues** [BEAST2-Dev/bdsky#29]
Hi All,
I'm trying to install the package but I receive this message: 

"Install failed because: No subject alternative DNS name matching github-releases.githubusercontent.com found"

The version of my BEAST is 2.5.2.

Regards,
Stephanie

**Comment by denisekuehnert** [comment]
This is a BEAST2 issue, that seems to have been solved for now, see https://github.com/CompEvol/beast2/issues/948
