### ISSUE TITLE
Cannot select Birth Death Skyline Contemporary in BEAUti

### ISSUE THREAD

**Issue by tgvaughan** [BEAST2-Dev/bdsky#9]
To reproduce in BEAST 2.4.3: install BDSKY, restart BEAUti, load an alignment, then select Birth Death Skyline Contemprary from the tree prior drop-down menu in the Priors panel. The selection is immediately replaced with Birth Death Skyline Multi Rho.  None of the other available tree prior options seem to have this problem.

(This came up in a workshop on Monday, preventing people from following along with the [Taming the BEAST skyline plot tutorial](https://www.ethz.ch/content/dam/ethz/special-interest/bsse/cevo/tamingthebeast/Materials/2016_06_28_Tuesday_11h00_Skyline.zip). )

**Comment by denisekuehnert** [comment]
Fixed.
